"""Cache-Control Rule Generator and Multi-Platform Exporters.

Generates production-grade caching and compression configuration for:
  - Netlify (_headers, netlify.toml)
  - Vercel (vercel.json)
  - Nginx (nginx.conf with Gzip & Brotli)
  - Cloudflare Pages / Workers (_headers, worker.js)
  - Next.js (next.config.js async headers)
  - Apache (.htaccess with mod_headers, mod_expires, mod_deflate)

Zero external runtime dependencies - pure Python stdlib.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from .compat import atomic_write_text, resolve_path


# Default rule blueprints
DEFAULT_STATIC_PATTERNS = [
    "/_next/static/*",
    "/assets/*",
    "/static/*",
    "/build/*",
    "/dist/*",
    "*.woff2",
    "*.woff",
    "*.ttf",
    "*.eot",
    "*.js",
    "*.css",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.webp",
    "*.avif",
    "*.svg",
    "*.gif",
    "*.ico",
]

HEADER_IMMUTABLE_STATIC = "public, max-age=31536000, immutable"
HEADER_HTML_REVALIDATE = "public, max-age=0, must-revalidate, stale-while-revalidate=86400"
HEADER_SERVICE_WORKER = "public, max-age=0, must-revalidate, no-cache"


def generate_netlify_headers(custom_rules: Optional[List[Dict[str, Any]]] = None) -> str:
    """Generate standard Netlify `_headers` configuration file content."""
    lines = [
        "# ==========================================================================",
        "# Netlify Cache-Control & Security Headers (Generated by CWV Speed Engine)",
        "# ==========================================================================",
        "",
        "# 1. Immutable Static Assets (Content-Hashed Bundles, Fonts & Images)",
        "/_next/static/*",
        f"  Cache-Control: {HEADER_IMMUTABLE_STATIC}",
        "/assets/*",
        f"  Cache-Control: {HEADER_IMMUTABLE_STATIC}",
        "/static/*",
        f"  Cache-Control: {HEADER_IMMUTABLE_STATIC}",
        "/build/*",
        f"  Cache-Control: {HEADER_IMMUTABLE_STATIC}",
        "/*.js",
        f"  Cache-Control: {HEADER_IMMUTABLE_STATIC}",
        "/*.css",
        f"  Cache-Control: {HEADER_IMMUTABLE_STATIC}",
        "/*.woff2",
        f"  Cache-Control: {HEADER_IMMUTABLE_STATIC}",
        "",
        "# 2. Service Workers, Manifests & Feeds (Always Revalidate)",
        "/sw.js",
        f"  Cache-Control: {HEADER_SERVICE_WORKER}",
        "/service-worker.js",
        f"  Cache-Control: {HEADER_SERVICE_WORKER}",
        "/manifest.json",
        f"  Cache-Control: {HEADER_SERVICE_WORKER}",
        "/sitemap.xml",
        "  Cache-Control: public, max-age=3600, stale-while-revalidate=86400",
        "",
        "# 3. HTML Pages & Dynamic Content (Fast Edge Delivery + SWR)",
        "/*",
        f"  Cache-Control: {HEADER_HTML_REVALIDATE}",
        "  X-Content-Type-Options: nosniff",
        "  X-Frame-Options: SAMEORIGIN",
        "  Referrer-Policy: strict-origin-when-cross-origin",
        "",
    ]

    if custom_rules:
        lines.append("# Custom User Rules")
        for rule in custom_rules:
            path = rule.get("path", "/*")
            lines.append(path)
            for k, v in rule.get("headers", {}).items():
                lines.append(f"  {k}: {v}")
            lines.append("")

    return "\n".join(lines)


def generate_netlify_toml(custom_rules: Optional[List[Dict[str, Any]]] = None) -> str:
    """Generate Netlify `netlify.toml` headers section."""
    lines = [
        "# ==========================================================================",
        "# Netlify TOML Headers (Generated by CWV Speed Engine)",
        "# ==========================================================================",
        "",
        "[[headers]]",
        '  for = "/_next/static/*"',
        "  [headers.values]",
        f'    Cache-Control = "{HEADER_IMMUTABLE_STATIC}"',
        "",
        "[[headers]]",
        '  for = "/assets/*"',
        "  [headers.values]",
        f'    Cache-Control = "{HEADER_IMMUTABLE_STATIC}"',
        "",
        "[[headers]]",
        '  for = "/static/*"',
        "  [headers.values]",
        f'    Cache-Control = "{HEADER_IMMUTABLE_STATIC}"',
        "",
        "[[headers]]",
        '  for = "/sw.js"',
        "  [headers.values]",
        f'    Cache-Control = "{HEADER_SERVICE_WORKER}"',
        "",
        "[[headers]]",
        '  for = "/*"',
        "  [headers.values]",
        f'    Cache-Control = "{HEADER_HTML_REVALIDATE}"',
        '    X-Content-Type-Options = "nosniff"',
        '    X-Frame-Options = "SAMEORIGIN"',
        '    Referrer-Policy = "strict-origin-when-cross-origin"',
        "",
    ]
    return "\n".join(lines)


def generate_vercel_json(custom_rules: Optional[List[Dict[str, Any]]] = None, pretty: bool = True) -> str:
    """Generate Vercel `vercel.json` headers configuration."""
    config: Dict[str, Any] = {
        "headers": [
            {
                "source": "/(assets|static|_next/static|build)/(.*)",
                "headers": [
                    {"key": "Cache-Control", "value": HEADER_IMMUTABLE_STATIC},
                ],
            },
            {
                "source": "/(.*)\\.(js|css|woff2|png|jpg|jpeg|webp|avif|svg|ico)",
                "headers": [
                    {"key": "Cache-Control", "value": HEADER_IMMUTABLE_STATIC},
                ],
            },
            {
                "source": "/(sw\\.js|service-worker\\.js|manifest\\.json)",
                "headers": [
                    {"key": "Cache-Control", "value": HEADER_SERVICE_WORKER},
                ],
            },
            {
                "source": "/(.*)",
                "headers": [
                    {"key": "Cache-Control", "value": HEADER_HTML_REVALIDATE},
                    {"key": "X-Content-Type-Options", "value": "nosniff"},
                    {"key": "X-Frame-Options", "value": "SAMEORIGIN"},
                    {"key": "Referrer-Policy", "value": "strict-origin-when-cross-origin"},
                ],
            },
        ],
    }

    if custom_rules:
        for rule in custom_rules:
            src = rule.get("path", "/(.*)")
            h_list = [{"key": k, "value": v} for k, v in rule.get("headers", {}).items()]
            config["headers"].append({"source": src, "headers": h_list})

    if pretty:
        return json.dumps(config, indent=2)
    return json.dumps(config)


def generate_nginx_conf(
    custom_rules: Optional[List[Dict[str, Any]]] = None,
    enable_gzip: bool = True,
    enable_brotli: bool = True,
) -> str:
    """Generate optimized Nginx server block configuration snippet."""
    lines = [
        "# ==========================================================================",
        "# Nginx CWV Speed & Cache Configuration (Generated by CWV Speed Engine)",
        "# ==========================================================================",
        "",
    ]

    if enable_gzip:
        lines.extend([
            "# 1. Gzip Compression",
            "gzip on;",
            "gzip_vary on;",
            "gzip_proxied any;",
            "gzip_comp_level 6;",
            "gzip_min_length 256;",
            "gzip_types",
            "    text/plain",
            "    text/css",
            "    text/xml",
            "    text/javascript",
            "    application/json",
            "    application/javascript",
            "    application/x-javascript",
            "    application/xml",
            "    application/xml+rss",
            "    application/vnd.ms-fontobject",
            "    font/ttf",
            "    font/opentype",
            "    image/svg+xml",
            "    image/x-icon;",
            "",
        ])

    if enable_brotli:
        lines.extend([
            "# 2. Brotli Compression (nginx-module-brotli)",
            "brotli on;",
            "brotli_comp_level 6;",
            "brotli_min_length 256;",
            "brotli_types",
            "    text/plain",
            "    text/css",
            "    text/xml",
            "    text/javascript",
            "    application/json",
            "    application/javascript",
            "    application/xml",
            "    application/xml+rss",
            "    image/svg+xml",
            "    font/woff2;",
            "",
        ])

    lines.extend([
        "# 3. Immutable Static Assets (1 Year Cache)",
        "location ~* ^/(assets|static|_next/static|build)/.*\\.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|webp|avif)$ {",
        "    expires 1y;",
        f'    add_header Cache-Control "{HEADER_IMMUTABLE_STATIC}";',
        "    access_log off;",
        "}",
        "",
        "# 4. Service Worker (Never Cache)",
        "location ~* ^/(sw\\.js|service-worker\\.js)$ {",
        "    expires -1;",
        f'    add_header Cache-Control "{HEADER_SERVICE_WORKER}";',
        "}",
        "",
        "# 5. HTML & SSR Pages (Stale-While-Revalidate)",
        "location ~* \\.html?$ {",
        f'    add_header Cache-Control "{HEADER_HTML_REVALIDATE}";',
        '    add_header X-Content-Type-Options "nosniff";',
        '    add_header X-Frame-Options "SAMEORIGIN";',
        '    add_header Referrer-Policy "strict-origin-when-cross-origin";',
        "}",
        "",
    ])

    return "\n".join(lines)


def generate_cloudflare_headers(custom_rules: Optional[List[Dict[str, Any]]] = None) -> str:
    """Generate Cloudflare Pages `_headers` file content."""
    # Cloudflare Pages uses standard _headers format identical to Netlify
    return generate_netlify_headers(custom_rules=custom_rules)


def generate_nextjs_config(custom_rules: Optional[List[Dict[str, Any]]] = None) -> str:
    """Generate Next.js (14/15) `next.config.js` headers snippet."""
    lines = [
        "/** @type {import('next').NextConfig} */",
        "const nextConfig = {",
        "  async headers() {",
        "    return [",
        "      {",
        '        source: "/:all*(svg|jpg|jpeg|png|webp|avif|ico|woff|woff2)",',
        "        headers: [",
        "          {",
        '            key: "Cache-Control",',
        f'            value: "{HEADER_IMMUTABLE_STATIC}",',
        "          },",
        "        ],",
        "      },",
        "      {",
        '        source: "/_next/static/:path*",',
        "        headers: [",
        "          {",
        '            key: "Cache-Control",',
        f'            value: "{HEADER_IMMUTABLE_STATIC}",',
        "          },",
        "        ],",
        "      },",
        "      {",
        '        source: "/sw.js",',
        "        headers: [",
        "          {",
        '            key: "Cache-Control",',
        f'            value: "{HEADER_SERVICE_WORKER}",',
        "          },",
        "        ],",
        "      },",
        "      {",
        '        source: "/:path*",',
        "        headers: [",
        "          {",
        '            key: "Cache-Control",',
        f'            value: "{HEADER_HTML_REVALIDATE}",',
        "          },",
        "          {",
        '            key: "X-Content-Type-Options",',
        '            value: "nosniff",',
        "          },",
        "          {",
        '            key: "Referrer-Policy",',
        '            value: "strict-origin-when-cross-origin",',
        "          },",
        "        ],",
        "      },",
        "    ];",
        "  },",
        "};",
        "",
        "module.exports = nextConfig;",
    ]
    return "\n".join(lines)


def generate_apache_htaccess(custom_rules: Optional[List[Dict[str, Any]]] = None) -> str:
    """Generate Apache `.htaccess` speed and caching configuration."""
    lines = [
        "# ==========================================================================",
        "# Apache .htaccess CWV Optimization (Generated by CWV Speed Engine)",
        "# ==========================================================================",
        "",
        "# 1. Gzip Compression (mod_deflate)",
        "<IfModule mod_deflate.c>",
        "    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css",
        "    AddOutputFilterByType DEFLATE application/javascript application/json application/xml",
        "    AddOutputFilterByType DEFLATE image/svg+xml image/x-icon font/woff font/woff2",
        "</IfModule>",
        "",
        "# 2. Browser Expires Headers (mod_expires)",
        "<IfModule mod_expires.c>",
        "    ExpiresActive On",
        "    ExpiresDefault \"access plus 1 month\"",
        "    ExpiresByType text/html \"access plus 0 seconds\"",
        "    ExpiresByType application/javascript \"access plus 1 year\"",
        "    ExpiresByType text/css \"access plus 1 year\"",
        "    ExpiresByType font/woff2 \"access plus 1 year\"",
        "    ExpiresByType image/webp \"access plus 1 year\"",
        "    ExpiresByType image/avif \"access plus 1 year\"",
        "</IfModule>",
        "",
        "# 3. Cache-Control & Security Headers (mod_headers)",
        "<IfModule mod_headers.c>",
        "    # Static Assets",
        "    <FilesMatch \"\\.(ico|pdf|flv|jpg|jpeg|png|gif|webp|avif|js|css|swf|woff|woff2|ttf|eot)$\">",
        f"        Header set Cache-Control \"{HEADER_IMMUTABLE_STATIC}\"",
        "    </FilesMatch>",
        "",
        "    # Service Worker",
        "    <FilesMatch \"^(sw|service-worker)\\.js$\">",
        f"        Header set Cache-Control \"{HEADER_SERVICE_WORKER}\"",
        "    </FilesMatch>",
        "",
        "    # HTML Pages",
        "    <FilesMatch \"\\.(html|htm)$\">",
        f"        Header set Cache-Control \"{HEADER_HTML_REVALIDATE}\"",
        "    </FilesMatch>",
        "</IfModule>",
        "",
    ]
    return "\n".join(lines)


FRAMEWORK_GENERATORS = {
    "netlify": generate_netlify_headers,
    "netlify_headers": generate_netlify_headers,
    "netlify_toml": generate_netlify_toml,
    "vercel": generate_vercel_json,
    "nginx": generate_nginx_conf,
    "cloudflare": generate_cloudflare_headers,
    "cloudflare_pages": generate_cloudflare_headers,
    "nextjs": generate_nextjs_config,
    "next": generate_nextjs_config,
    "apache": generate_apache_htaccess,
    "htaccess": generate_apache_htaccess,
}

DEFAULT_FILENAMES = {
    "netlify": "_headers",
    "netlify_headers": "_headers",
    "netlify_toml": "netlify.toml",
    "vercel": "vercel.json",
    "nginx": "nginx.conf",
    "cloudflare": "_headers",
    "cloudflare_pages": "_headers",
    "nextjs": "next.config.js",
    "next": "next.config.js",
    "apache": ".htaccess",
    "htaccess": ".htaccess",
}


def generate_cache_headers(
    framework_or_server: str = "netlify",
    custom_rules: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """Generate full caching configuration for the requested hosting framework or web server.

    Args:
        framework_or_server: Target framework ('netlify', 'vercel', 'nginx', 'cloudflare', 'nextjs', 'apache').
        custom_rules: Optional list of custom path and header rules.

    Returns:
        Dict with framework name, recommended filename, content, and description.
    """
    key = framework_or_server.lower().strip()
    generator = FRAMEWORK_GENERATORS.get(key, generate_netlify_headers)
    filename = DEFAULT_FILENAMES.get(key, "_headers")

    content = generator(custom_rules=custom_rules)

    return {
        "framework": key,
        "default_filename": filename,
        "content": content,
        "static_cache_control": HEADER_IMMUTABLE_STATIC,
        "html_cache_control": HEADER_HTML_REVALIDATE,
    }


def export_cache_config(
    target: str = "netlify",
    output_path: Optional[Union[str, Path]] = None,
    custom_rules: Optional[List[Dict[str, Any]]] = None,
) -> Dict[str, Any]:
    """Generate and optionally write cache configuration to disk atomically.

    Args:
        target: Target server or hosting platform.
        output_path: Destination file path. If omitted, uses default filename.
        custom_rules: Optional custom header rules.

    Returns:
        Dict with destination path, content, and write status.
    """
    result = generate_cache_headers(framework_or_server=target, custom_rules=custom_rules)
    dest_path = resolve_path(output_path) if output_path else Path(result["default_filename"]).resolve()

    written_path = atomic_write_text(dest_path, result["content"])

    return {
        "framework": result["framework"],
        "path": str(written_path),
        "content": result["content"],
        "written": True,
    }
